language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: libsodium
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; sudo add-apt-repository -y ppa:chris-lea/libsodium; sudo apt-get update -q; sudo apt-get install -y libsodium-dev; fi

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
