language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: libsodium
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

# PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
