language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.1
      brew_packages: libsodium
      latex: false
    - os: osx
      osx_image: beta-xcode6.4
      disable_homebrew: true

r_github_packages:
  - jimhester/covr

addons:
  apt:
    sources:
      - chris-lea/libsodium
    packages:
      - libsodium-dev
      - valgrind

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
