language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8
      brew_packages: libsodium
      latex: false
      before_install: ''
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      before_install: ''

r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
    - valgrind

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update -q
  - sudo apt-get install -y libsodium-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
